DROP TABLE LOAN_TRANSACTION;
DROP TABLE LOAN;
DROP TABLE ONE_TIME;
DROP TABLE VEHICLE;
DROP TABLE VEHICLE_TRANSACTION;

DROP SEQUENCE VEHICLE_TRANSACTION_SEQUENCE;
DROP SEQUENCE LOAN_TRANSACTION_SEQUENCE;