DROP TABLE LOAN_TRANSACTION;
DROP TABLE LOAN;
DROP TABLE ONE_TIME;
DROP TABLE VEHICLE;
DROP TABLE VEHICLE_TRANSACTION;

DROP SEQUENCE VEHICLE_TRANSACTION_SEQUENCE;
DROP SEQUENCE LOAN_TRANSACTION_SEQUENCE;

CREATE TABLE IF NOT EXISTS VEHICLE(
VEHICLE_NAME varchar(150),
VEHICLE_NUMBER varchar(50),
VEHICLE_TYPE varchar(20),
VEHICLE_STATUS varchar(20),
VEHICLE_COST BIGINT,
VEHICLE_LOANS varchar(300),
INVESTMENT BIGINT,
);

ALTER TABLE VEHICLE ALTER COLUMN VEHICLE_NAME SET NOT NULL;
ALTER TABLE VEHICLE ADD PRIMARY KEY (VEHICLE_NAME);


CREATE TABLE IF NOT EXISTS LOAN(
LOAN_NAME varchar(50),
LOAN_DESCRIPTION varchar(150),
LOAN_START_DATE DATE,
LOAN_END_DATE DATE,
LOAN_AMOUNT long,
LOAN_STATUS varchar(20),
LOAN_PERIOD int
);

ALTER TABLE LOAN ALTER COLUMN LOAN_NAME SET NOT NULL;
ALTER TABLE LOAN ADD PRIMARY KEY (LOAN_NAME);

CREATE TABLE IF NOT EXISTS VEHICLE_TRANSACTION(
VEHICLE_NAME varchar(150),
SEQUENCE_NUMBER int,
DESCRIPTION varchar(150),
TRANSACTION_DATE DATE,
TRANSACTION_TYPE varchar(20),
TRANSACTION_ATTRIBUTE varchar(20),
AMOUNT int,
LAST_UPDATED_TIME timestamp
);

ALTER TABLE VEHICLE_TRANSACTION ALTER COLUMN VEHICLE_NAME SET NOT NULL;
ALTER TABLE VEHICLE_TRANSACTION ALTER COLUMN SEQUENCE_NUMBER SET NOT NULL;
ALTER TABLE VEHICLE_TRANSACTION ADD PRIMARY KEY (VEHICLE_NAME, SEQUENCE_NUMBER);

CREATE TABLE IF NOT EXISTS LOAN_TRANSACTION(
LOAN_NAME varchar(50),
SEQUENCE_NUMBER int,
DESCRIPTION varchar(150),
TRANSACTION_DATE DATE,
TRANSACTION_TYPE varchar(20),
AMOUNT int,
LAST_UPDATED_TIME timestamp
);

ALTER TABLE LOAN_TRANSACTION ALTER COLUMN LOAN_NAME SET NOT NULL;
ALTER TABLE LOAN_TRANSACTION ALTER COLUMN SEQUENCE_NUMBER SET NOT NULL;
ALTER TABLE LOAN_TRANSACTION ADD PRIMARY KEY (LOAN_NAME, SEQUENCE_NUMBER);

CREATE TABLE IF NOT EXISTS ONE_TIME(
FIELD_TYPE varchar(50),
FIELD_VAL varchar(20)
);

ALTER TABLE ONE_TIME ALTER COLUMN FIELD_TYPE SET NOT NULL;
ALTER TABLE ONE_TIME ALTER COLUMN FIELD_VAL SET NOT NULL;
ALTER TABLE ONE_TIME ADD PRIMARY KEY (FIELD_TYPE, FIELD_VAL);

CREATE SEQUENCE IF NOT EXISTS VEHICLE_TRANSACTION_SEQUENCE START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE IF NOT EXISTS LOAN_TRANSACTION_SEQUENCE START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('loan_status',  'Running');
INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('loan_status',  'Closed');

INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('loan_txn_type', 'EMI');
INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('loan_txn_type', 'Interest');
INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('loan_txn_type', 'Part-Payment');

INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('vehicle_type', 'Lorry');

INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('vehicle_status', 'Active');
INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('vehicle_status', 'Inactive');

INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('vehicle_txn_type', 'Credit');
INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('vehicle_txn_type', 'Debit');

INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('vehicle_txn_attribute', 'Fuel');
INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('vehicle_txn_attribute', 'Tollgate');
INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('vehicle_txn_attribute', 'Driver-Payment');
INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('vehicle_txn_attribute', 'Earning');
INSERT INTO ONE_TIME (FIELD_TYPE, FIELD_VAL) values ('vehicle_txn_attribute', 'Others');
